"""DFM output parity tests.

Verify that _analyze_single_process produces the same output as the baseline
JSON files captured in tests/assets/baselines/. Run after every optimization
tier to catch unintended DFM behaviour changes.

Baselines are regenerated by:
    python tests/generate_dfm_baselines.py

Comparison rules:
- Integer count fields: exact match.
- Boolean / risk fields: exact match.
- Float fields (areas, volumes): within 1% relative tolerance.
- Region coordinate lists: sorted + rounded to 2dp before comparison.
- `issues` list: compared by (category, severity, title) tuples only
  (description text may change independently of the DFM output).
- `twoPhaseDeferred` and timing fields are ignored.
"""

import json
from pathlib import Path

import pytest

from src.core.geometry import _analyze_single_process

ASSETS = Path(__file__).parent / "assets"
BASELINES = Path(__file__).parent / "assets" / "baselines"

# Fields whose values must match exactly (ints + booleans)
EXACT_INT_FIELDS = {
    "thinWallCount",
    "overhangFaceCount",
    "sharpCornerCount",
    "drillHoleCount",
    "chatterRiskCount",
}
EXACT_BOOL_FIELDS = {
    "supportRequired",
    "isManifold",
    "hasDrillHoles",
    "hasUndercuts",
    "requiresEdm",
    "requiresGrinding",
    "resinTrappingRisk",
    "suctionRisk",
}
# Float fields allowed 1% relative tolerance
FLOAT_FIELDS = {
    "overhangAreaCm2",
    "estimatedSupportVolumeCm3",
    "minimumFeatureSizeMm",
    "smallDetailCount",
}


def _sort_regions(v: object) -> object:
    """Recursively sort region lists (list-of-[x,y,z]) for order-independence.
    Scalar floats are left unchanged so pytest.approx can compare them properly.
    """
    if isinstance(v, list):
        if v and isinstance(v[0], list):
            return sorted([sorted(inner) for inner in v])
        return [_sort_regions(i) for i in v]
    if isinstance(v, dict):
        return {k: _sort_regions(vv) for k, vv in v.items()}
    return v


def _normalize_report(report: dict) -> dict:
    skip = {"twoPhaseDeferred"}
    return {k: _sort_regions(v) for k, v in report.items() if k not in skip}


def _issues_key(issue: dict) -> tuple:
    return (
        issue.get("category", ""),
        issue.get("severity", ""),
        issue.get("title", ""),
    )


def _load_cases() -> list[tuple[Path, str, Path]]:
    """Return list of (stl_path, process_code, baseline_path) tuples."""
    cases = []
    for baseline_path in sorted(BASELINES.glob("*__*.json")):
        stem, process_code = baseline_path.stem.rsplit("__", 1)
        stl_path = ASSETS / f"{stem}.stl"
        if stl_path.exists():
            cases.append((stl_path, process_code, baseline_path))
    return cases


def pytest_generate_tests(metafunc: pytest.Metafunc) -> None:
    if "parity_case" in metafunc.fixturenames:
        cases = _load_cases()
        ids = [f"{c[0].stem}__{c[1]}" for c in cases]
        metafunc.parametrize("parity_case", cases, ids=ids)


def test_dfm_parity(parity_case: tuple[Path, str, Path]) -> None:
    stl_path, process_code, baseline_path = parity_case

    stl_bytes = stl_path.read_bytes()
    baseline = json.loads(baseline_path.read_text())

    result = _analyze_single_process(stl_bytes, process_code)
    assert (
        "error_type" not in result
    ), f"Analysis failed for {stl_path.name} [{process_code}]: {result}"

    current = _normalize_report(result)

    # --- Exact integer counts ---
    for field in EXACT_INT_FIELDS:
        if field in baseline:
            assert int(current.get(field, -1)) == int(baseline[field]), (
                f"{stl_path.name} [{process_code}] {field}: "
                f"got {current.get(field)}, expected {baseline[field]}"
            )

    # --- Exact boolean flags ---
    for field in EXACT_BOOL_FIELDS:
        if field in baseline:
            assert current.get(field) == baseline[field], (
                f"{stl_path.name} [{process_code}] {field}: "
                f"got {current.get(field)}, expected {baseline[field]}"
            )

    # --- Float fields within 5% relative (or 0.05 absolute for near-zero) ---
    for field in FLOAT_FIELDS:
        if field in baseline and baseline[field] is not None:
            got = current.get(field)
            exp = baseline[field]
            if abs(exp) < 0.01:
                assert (
                    got == pytest.approx(exp, abs=0.05)
                ), f"{stl_path.name} [{process_code}] {field}: got {got}, expected {exp}"  # noqa: E501
            else:
                assert (
                    got == pytest.approx(exp, rel=0.05)
                ), f"{stl_path.name} [{process_code}] {field}: got {got}, expected {exp}"  # noqa: E501

    # --- Issues list — compare by (category, severity, title) ---
    if "issues" in baseline:
        baseline_issue_keys = sorted(_issues_key(i) for i in baseline["issues"])
        current_issue_keys = sorted(_issues_key(i) for i in current.get("issues", []))
        assert current_issue_keys == baseline_issue_keys, (
            f"{stl_path.name} [{process_code}] issues mismatch:\n"
            f"  got:      {current_issue_keys}\n"
            f"  expected: {baseline_issue_keys}"
        )
