"""Golden-result regression tests for DFM analysis.

Runs the full Phase 1 + Phase 2 pipeline against curated STEP fixtures and
asserts the resulting issues fall within hand-labeled expected ranges.

Each fixture has a sibling ``*.expectations.json`` describing what each
process should and should not detect.  The test parametrizes over the
cross-product of (fixture, process) and asserts:

* every category listed under ``must_have`` fires within ``count_min..count_max``
  with a severity at least ``severity_min``
* every category listed under ``must_not_have`` does NOT fire (count == 0)

Fixtures are generated by ``tests/fixtures/dfm/generate/*.py`` cadquery scripts;
regenerate via ``poetry run python tests/fixtures/dfm/generate/generate_all.py``.

When detector accuracy improves and a previously-firing category goes silent
(or vice-versa), update the fixture's ``expectations.json`` deliberately —
this test is the authoritative spec of detector behavior.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from src.core.geometry import (
    _analyze_single_process,
    _compute_metrics_worker,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "dfm"

# Severity ordering: higher index = more severe.  Used for severity_min checks.
SEVERITY_ORDER = ["info", "warning", "error", "critical"]


def severity_rank(severity: str) -> int:
    try:
        return SEVERITY_ORDER.index(severity)
    except ValueError:
        return -1


def _discover_cases() -> list[tuple[str, str]]:
    """Build (fixture_name, process_code) parameter pairs from expectation JSONs."""
    cases: list[tuple[str, str]] = []
    if not FIXTURE_DIR.exists():
        return cases
    for exp_path in sorted(FIXTURE_DIR.glob("*.expectations.json")):
        fixture_name = exp_path.stem.replace(".expectations", "")
        step_path = FIXTURE_DIR / f"{fixture_name}.step"
        if not step_path.exists():
            continue
        spec = json.loads(exp_path.read_text())
        for proc in spec.get("process_expectations", {}):
            cases.append((fixture_name, proc))
    return cases


# Module-scoped cache: tessellate each fixture exactly once across the
# parametrized test runs to keep the suite fast on CI.
_metrics_cache: dict[str, dict[str, Any]] = {}


def _get_metrics(fixture_name: str) -> dict[str, Any]:
    cached = _metrics_cache.get(fixture_name)
    if cached is not None:
        return cached
    step_path = FIXTURE_DIR / f"{fixture_name}.step"
    cad_bytes = step_path.read_bytes()
    metrics = _compute_metrics_worker(cad_bytes, "step")
    metrics["_cad_bytes"] = cad_bytes
    _metrics_cache[fixture_name] = metrics
    return metrics


def _categorize(issues: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Group issues by category, retaining max severity per group."""
    grouped: dict[str, dict[str, Any]] = {}
    for iss in issues:
        cat = iss.get("category", "unknown")
        sev = iss.get("severity", "info")
        bucket = grouped.setdefault(cat, {"count": 0, "max_severity_rank": -1})
        bucket["count"] += 1
        bucket["max_severity_rank"] = max(
            bucket["max_severity_rank"], severity_rank(sev)
        )
    return grouped


@pytest.mark.parametrize(("fixture_name", "process_code"), _discover_cases())
def test_dfm_golden(fixture_name: str, process_code: str) -> None:
    spec_path = FIXTURE_DIR / f"{fixture_name}.expectations.json"
    spec = json.loads(spec_path.read_text())

    metrics = _get_metrics(fixture_name)
    stl_bytes = metrics.get("mesh_stl_bytes") or b""
    cad_bytes = metrics["_cad_bytes"]
    assert stl_bytes, f"{fixture_name}: tessellation produced no STL bytes"

    # Metrics-level expectations (body count, triangle count) are checked once
    # per fixture by piggy-backing on the FDM parametrization.
    if process_code == "FDM":
        metrics_spec = spec.get("metrics_expectations") or {}
        body_spec = metrics_spec.get("body_count") or {}
        if "min" in body_spec:
            assert metrics.get("body_count", 0) >= body_spec["min"], (
                f"{fixture_name}: body_count "
                f"{metrics.get('body_count')} < min {body_spec['min']}"
            )
        if "max" in body_spec:
            assert metrics.get("body_count", 0) <= body_spec["max"], (
                f"{fixture_name}: body_count "
                f"{metrics.get('body_count')} > max {body_spec['max']}"
            )
        tri_min = metrics_spec.get("triangle_count_min")
        if tri_min is not None:
            assert metrics.get("triangle_count", 0) >= tri_min, (
                f"{fixture_name}: triangle_count "
                f"{metrics.get('triangle_count')} < min {tri_min} — "
                "multi-body STL likely dropping bodies"
            )

    report = _analyze_single_process(stl_bytes, process_code, cad_bytes, "step")
    if "error_type" in report:
        pytest.fail(
            f"{fixture_name}/{process_code}: analysis errored: {report.get('message')}"
        )

    grouped = _categorize(report.get("issues", []))
    proc_spec = spec["process_expectations"][process_code]

    for cat, expect in (proc_spec.get("must_have") or {}).items():
        bucket = grouped.get(cat)
        assert bucket is not None, (
            f"{fixture_name}/{process_code}: category '{cat}' not detected "
            f"(detected categories: {sorted(grouped)})"
        )
        cmin = expect.get("count_min", 1)
        cmax = expect.get("count_max", 9999)
        assert cmin <= bucket["count"] <= cmax, (
            f"{fixture_name}/{process_code}: '{cat}' count "
            f"{bucket['count']} outside [{cmin}, {cmax}]"
        )
        sev_min = expect.get("severity_min")
        if sev_min is not None:
            sev_min_rank = severity_rank(sev_min)
            assert bucket["max_severity_rank"] >= sev_min_rank, (
                f"{fixture_name}/{process_code}: '{cat}' max severity rank "
                f"{bucket['max_severity_rank']} < required {sev_min_rank} ({sev_min})"
            )

    for cat in proc_spec.get("must_not_have", []):
        if cat in grouped:
            pytest.fail(
                f"{fixture_name}/{process_code}: forbidden category '{cat}' "
                f"detected (count={grouped[cat]['count']})"
            )
